endOfLine: auto
htmlWhitespaceSensitivity: strict
printWidth: 120
tabWidth: 4
trailingComma: all
overrides:
  - files: "*.html"
    options:
      parser: html
  - files:
      - "*.yml"
      - "*.yaml"
      - ".snyk"
    options:
      tabWidth: 2
